workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "master" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always

stages:
#  - test # TODO
#  - build # TODO
  - deploy

# TODO
#test:
#  stage: test
#  image: node:16.13-alpine

#build_atpools_contact:
#  stage: build

deploy_frontend:
  stage: deploy
  before_script:
    - chmod 400 $WS_KEY
  script:
    - scp -o StrictHostKeyChecking=no -i $WS_KEY -r frontend/* ubuntu@$WS_HOST:/home/ubuntu/applications/share/nginx/html/atpools
  environment:
    name: development
    url: https://$WS_HOST:443