version: "3.5"

services:

  backend:
    container_name: atpools_backend
    restart: always
    image: ${DC_IMAGE_NAME}:${DC_IMAGE_TAG}
    ports:
      - 3001:3001
    networks:
      - common_network
    environment:
      - MAIL_USERNAME=$MAIL_USERNAME
      - MAIL_PASSWORD=$MAIL_PASSWORD
      - OAUTH_CLIENTID=$OAUTH_CLIENTID
      - OAUTH_CLIENT_SECRET=$OAUTH_CLIENT_SECRET
      - OAUTH_REFRESH_TOKEN=$OAUTH_REFRESH_TOKEN
      - ACCESS_TOKEN=$ACCESS_TOKEN
      - RECEIVING_EMAILS=$RECEIVING_EMAILS

networks:
  common_network:
    external:
      name: common_network  # must match the actual name of the network created in the external file